[tool.poetry]
name = "polus-images-features-region-segmentation-eval"
version = "0.2.6"
description = ""
authors = [
           "Vishakha Goyal <vishakha.goyal@nih.gov>",
           "Hamdah Shafqat Abbasi <hamdahshafqat.abbasi@nih.gov>"
           ]
readme = "README.md"
packages = [{include = "polus", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9"
bfio = {version = "2.1.9", extras = ["all"]}
filepattern = "^2.0.1"
typer = "^0.7.0"
tqdm = "^4.64.1"
scikit-image = "^0.19.3"
opencv_python="^4.5.1.48"
tifffile="^2020.10.1"
blake3 = "^0.3.3"
fastapi = "^0.92.0"
vaex = "^4.7.0"
numpy = "<2.0.0"
pyarrow = ">=16.0,<17.0"
scikit-learn = "^1.5.1"
numba = "^0.60.0"
llvmlite = "^0.43.0"

[tool.poetry.group.dev.dependencies]
bump2version = "^1.0.1"
pre-commit = "^3.0.4"
black = "^23.1.0"
flake8 = "^6.0.0"
mypy = "^1.0.0"
pytest = "^7.2.1"
ipykernel = "^6.21.2"
requests = "^2.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
